apiVersion: v1
kind: Service
metadata:
  name: demo-app-active
  namespace: demo-app
  labels:
    app: demo-app
    role: stable
    managed-by: emmanuel-ubani
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
